version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: avinashchh/data-persistence
    container_name: data-persistence--sample
    restart: always
    
    ports:
      - 3000:4000
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    

  mongo_db:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 3000:4000
    volumes:     
      - dbdata:/data/db
    environment:
      Port: 4000
      mongodb_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
      NAME: Raja
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:  

