version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: avinashchh/data-persistence
    container_name: data-persistence--sample
    restart: always
    
    ports:
      - 90:8080
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    

  mongodb:
    image: mongo: latest
    container_name: mongodb
    restart: always
    
    volumes:     
      - dbdata:/data/db
    environment:
      Port:90
      mongodb_URI= mongodb://mongo_db:27017
      DB_NAME= my_db
      NAME=Raja
    depends_on:
      -mongo_db
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:  

